# Generated by Django 4.2.30 on 2026-05-05 03:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('celular', models.CharField(max_length=15, unique=True)),
                ('fecha_registro', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Motocicleta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('placa', models.CharField(max_length=10, unique=True)),
                ('modelo', models.CharField(max_length=100)),
                ('propietario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='motos', to='motoflow_core.cliente')),
            ],
        ),
        migrations.CreateModel(
            name='OrdenTrabajo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_ingreso', models.DateTimeField(auto_now_add=True)),
                ('estado', models.CharField(choices=[('taller', 'En Taller'), ('listo', 'Listo para Retiro'), ('entregado', 'Entregado')], default='taller', max_length=20)),
                ('audio_nota', models.FileField(blank=True, null=True, upload_to='audios/')),
                ('total_cobro', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('moto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='motoflow_core.motocicleta')),
            ],
        ),
        migrations.CreateModel(
            name='EventoMuro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('foto', 'Foto de Evidencia'), ('nota', 'Nota de Voz'), ('tarea', 'Tarea Completada')], max_length=10)),
                ('contenido_texto', models.TextField(blank=True)),
                ('archivo', models.FileField(blank=True, null=True, upload_to='muro/')),
                ('fecha', models.DateTimeField(auto_now_add=True)),
                ('orden', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='eventos', to='motoflow_core.ordentrabajo')),
            ],
        ),
    ]
