# Generated by Django 4.2.30 on 2026-05-11 07:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('motoflow_core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='eventomuro',
            name='completada',
            field=models.BooleanField(default=False),
        ),
    ]
