# Generated by Django 4.2.30 on 2026-05-13 02:22

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('motoflow_core', '0002_eventomuro_completada'),
    ]

    operations = [
        migrations.AddField(
            model_name='ordentrabajo',
            name='hash_seguimiento',
            field=models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
        ),
    ]
