# Generated by Django 4.2.30 on 2026-05-28 06:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('motoflow_core', '0004_cotizacion_itemcotizacion'),
    ]

    operations = [
        migrations.AddField(
            model_name='cotizacion',
            name='contexto',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='cotizacion',
            name='foto_evidencia',
            field=models.FileField(blank=True, null=True, upload_to='cotizaciones/'),
        ),
    ]
