# Generated by Django 4.2.30 on 2026-05-29 03:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('motoflow_core', '0005_cotizacion_contexto_cotizacion_foto_evidencia'),
    ]

    operations = [
        migrations.AddField(
            model_name='ordentrabajo',
            name='fecha_entrega',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
