# Generated by Django 4.2.30 on 2026-05-29 06:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('motoflow_core', '0006_ordentrabajo_fecha_entrega'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cotizacion',
            name='orden',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cotizaciones', to='motoflow_core.ordentrabajo'),
        ),
    ]
